defaults: &defaults
  app_name: "RATAB"

development:
  <<: *defaults
  BASE_URL: 'http://172.16.27.29:3000'
  email_sender: "RATAB测试邮件"

test:
  <<: *defaults
  email_sender: "RATAB测试邮件"

production:
  <<: *defaults
  email_sender: "RATAB自动邮件"
